// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VideoGameCharacterApi.Data;

#nullable disable

namespace VideoGameCharacterApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260728215851_AddStudentTables")]
    partial class AddStudentTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.7");

            modelBuilder.Entity("VideoGameCharacterApi.Data.Models.Character", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ColorId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CreationDate")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Game")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<int?>("TypeId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ColorId");

                    b.HasIndex("TypeId");

                    b.ToTable("Characters");
                });

            modelBuilder.Entity("VideoGameCharacterApi.Data.Models.CharacterColor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ColorName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("CharacterColors");
                });

            modelBuilder.Entity("VideoGameCharacterApi.Data.Models.CharacterType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("CharacterTypes");
                });

            modelBuilder.Entity("VideoGameCharacterApi.Data.Models.Character", b =>
                {
                    b.HasOne("VideoGameCharacterApi.Data.Models.CharacterColor", "Color")
                        .WithMany()
                        .HasForeignKey("ColorId");

                    b.HasOne("VideoGameCharacterApi.Data.Models.CharacterType", "Type")
                        .WithMany()
                        .HasForeignKey("TypeId");

                    b.Navigation("Color");

                    b.Navigation("Type");
                });
#pragma warning restore 612, 618
        }
    }
}
